name: Invite to Organization

on:
  repository_dispatch:
    types: [join_organization]

jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get user information
        id: user-info
        run: |
          echo "::set-output name=username::${{ github.event.client_payload.github_username }}"
          echo "::set-output name=email::${{ github.event.client_payload.email }}"

      - name: Invite user to organization
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            const username = '${{ steps.user-info.outputs.username }}';
            const email = '${{ steps.user-info.outputs.email }}';
            
            try {
              // Check if user exists
              await github.rest.users.getByUsername({
                username: username
              });
              
              // Send organization invitation
              await github.rest.orgs.createInvitation({
                org: 'THE-NIS-KENYA',
                email: email,
                role: 'direct_member'
              });
              
              console.log(`Successfully invited ${username} to the organization`);
            } catch (error) {
              console.error(`Error inviting user: ${error.message}`);
              core.setFailed(error.message);
            }

      - name: Send confirmation email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Welcome to THE NIS Kenya!"
          to: ${{ steps.user-info.outputs.email }}
          from: THE NIS Kenya
          body: |
            Hello ${{ steps.user-info.outputs.username }},
            
            Thank you for your interest in joining THE NIS Kenya. We have sent you an invitation to join our GitHub organization.
            
            Please check your GitHub notifications or email for the invitation link.
            
            Best regards,
            THE NIS Kenya Team
